// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpZ5FM_L0V9nd1r3dFcaEoYnYtha-YwIo',
    appId: '1:707403014339:web:0134890aa9a294b8fbc276',
    messagingSenderId: '707403014339',
    projectId: 'movieauthproject',
    authDomain: 'movieauthproject.firebaseapp.com',
    storageBucket: 'movieauthproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1mdnQF873t1nWr4OE4FrRXI4OX_YfKiU',
    appId: '1:707403014339:android:25b47cd197226e2ffbc276',
    messagingSenderId: '707403014339',
    projectId: 'movieauthproject',
    storageBucket: 'movieauthproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu9BLEJP5RTjkx4U5iQvaIuxp_KQaZKtk',
    appId: '1:707403014339:ios:858cf8a2deb8ffe7fbc276',
    messagingSenderId: '707403014339',
    projectId: 'movieauthproject',
    storageBucket: 'movieauthproject.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu9BLEJP5RTjkx4U5iQvaIuxp_KQaZKtk',
    appId: '1:707403014339:ios:858cf8a2deb8ffe7fbc276',
    messagingSenderId: '707403014339',
    projectId: 'movieauthproject',
    storageBucket: 'movieauthproject.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpZ5FM_L0V9nd1r3dFcaEoYnYtha-YwIo',
    appId: '1:707403014339:web:84698f85ad0a20c2fbc276',
    messagingSenderId: '707403014339',
    projectId: 'movieauthproject',
    authDomain: 'movieauthproject.firebaseapp.com',
    storageBucket: 'movieauthproject.appspot.com',
  );
}
